application: my-app-id
version: 3-1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /fetcher
  script: fetcher.py
  login: admin
- url: /jsgraph
  script: graph_js.application
- url: /css
  static_dir: css
- url: /robots\.txt
  static_files: robots/robots.txt
  upload: robots/robots.txt
- url: /favicon\.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico
- url: /apple-touch-icon\.png
  static_files: media/apple-touch-icon.png
  upload: media/apple-touch-icon.png
- url: /apple-touch-icon-precomposed\.png
  static_files: media/apple-touch-icon.png
  upload: media/apple-touch-icon.png
- url: /apple-touch-icon-72x72\.png
  static_files: media/apple-touch-icon-72x72.png
  upload: media/apple-touch-icon-72x72.png
- url: /apple-touch-icon-72x72-precomposed\.png
  static_files: media/apple-touch-icon-72x72.png
  upload: media/apple-touch-icon-72x72.png
- url: /*
  script: graph.application

libraries:
- name: webapp2
  version: latest
- name: matplotlib
  version: latest
