application: my-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /fetcher
  script: fetcher.py
  login: admin
- url: /robots.txt
  static_files: robots/robots.txt
  upload: robots/robots.txt
- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico
- url: /*
  script: graph.application

libraries:
- name: webapp2
  version: latest
- name: matplotlib
  version: latest
