application: my-app
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /fetcher
  script: fetcher.py
  login: admin
- url: /
  script: graph.application

libraries:
- name: webapp2
  version: latest
- name: matplotlib
  version: latest
